<?php
$vendorCollection = $block->getVendorCollection();
if (count($vendorCollection)):
?>
<table border=1>
    <thead>
        <tr>
            <th>ID</th>
            <th>Vendor Name</th>
            <th>Vendor Description</th>
            <th>Vendor Email</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($vendorCollection as $vendor): ?>
            <tr>
                <td><?php echo $vendor->getId(); ?></td>
                <td><?php echo $vendor->getName(); ?></td>
                <td><?php echo $vendor->getDescription(); ?></td>
                <td><?php echo $vendor->getEmail(); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
<p>No vendors found.</p>
<?php endif; ?>
